# Jeu de donnees factice pour la demo SnapDevis Entretien (entretien d'espaces verts).
# Prix plausibles mais inventes, aucune reference a un vrai tarif ou fournisseur.

PRODUITS_DEMO: list[dict] = [
    {"designation": "Tonte pelouse standard", "unite": "m2", "prix": 0.35, "categorie": "tonte"},
    {"designation": "Tonte pelouse en pente ou difficile d'acces", "unite": "m2", "prix": 0.55, "categorie": "tonte"},
    {"designation": "Debroussaillage leger", "unite": "m2", "prix": 0.60, "categorie": "tonte"},
    {"designation": "Debroussaillage epais / friche", "unite": "m2", "prix": 1.10, "categorie": "tonte"},
    {"designation": "Aeration et scarification de pelouse", "unite": "m2", "prix": 0.90, "categorie": "tonte"},
    {"designation": "Ramassage et evacuation de l'herbe coupee", "unite": "m2", "prix": 0.15, "categorie": "evacuation"},
    {"designation": "Taille de haie basse (moins de 1,5 m)", "unite": "ml", "prix": 4.50, "categorie": "taille"},
    {"designation": "Taille de haie moyenne (1,5 a 3 m)", "unite": "ml", "prix": 7.80, "categorie": "taille"},
    {"designation": "Taille de haie haute (plus de 3 m, nacelle)", "unite": "ml", "prix": 13.00, "categorie": "taille"},
    {"designation": "Taille d'arbuste isole", "unite": "unite", "prix": 12.00, "categorie": "taille"},
    {"designation": "Taille de rosiers", "unite": "unite", "prix": 6.50, "categorie": "taille"},
    {"designation": "Elagage leger d'arbre (moins de 4 m)", "unite": "unite", "prix": 45.00, "categorie": "taille"},
    {"designation": "Desherbage manuel de massifs", "unite": "m2", "prix": 3.20, "categorie": "desherbage"},
    {"designation": "Desherbage thermique d'allees", "unite": "ml", "prix": 2.10, "categorie": "desherbage"},
    {"designation": "Desherbage mecanique (binage)", "unite": "m2", "prix": 2.60, "categorie": "desherbage"},
    {"designation": "Plantation arbuste godet", "unite": "unite", "prix": 18.00, "categorie": "plantation"},
    {"designation": "Plantation arbuste conteneur 10L", "unite": "unite", "prix": 32.00, "categorie": "plantation"},
    {"designation": "Plantation vivace", "unite": "unite", "prix": 6.00, "categorie": "plantation"},
    {"designation": "Plantation de haie (jeunes plants)", "unite": "ml", "prix": 22.00, "categorie": "plantation"},
    {"designation": "Engazonnement par semis", "unite": "m2", "prix": 4.50, "categorie": "plantation"},
    {"designation": "Engazonnement par placage de gazon", "unite": "m2", "prix": 11.00, "categorie": "plantation"},
    {"designation": "Evacuation de dechets verts (benne)", "unite": "m3", "prix": 28.00, "categorie": "evacuation"},
    {"designation": "Broyage de vegetaux sur site", "unite": "m3", "prix": 18.00, "categorie": "evacuation"},
    {"designation": "Ramassage de feuilles mortes (automne)", "unite": "m2", "prix": 0.45, "categorie": "evacuation"},
    {"designation": "Engrais gazon organique", "unite": "sac 20kg", "prix": 34.00, "categorie": "fertilisation"},
    {"designation": "Engrais massifs et arbustes", "unite": "sac 10kg", "prix": 22.00, "categorie": "fertilisation"},
    {"designation": "Amendement en terre vegetale", "unite": "m3", "prix": 45.00, "categorie": "fertilisation"},
    {"designation": "Paillage ecorces de pin", "unite": "m2", "prix": 5.50, "categorie": "paillage"},
    {"designation": "Paillage copeaux de bois", "unite": "m2", "prix": 4.20, "categorie": "paillage"},
    {"designation": "Paillage mineral (galets)", "unite": "m2", "prix": 8.90, "categorie": "paillage"},
    {"designation": "Installation paillage geotextile", "unite": "m2", "prix": 3.50, "categorie": "paillage"},
    {"designation": "Traitement phytosanitaire preventif", "unite": "m2", "prix": 1.80, "categorie": "traitement"},
    {"designation": "Traitement anti-mousse pelouse", "unite": "m2", "prix": 1.20, "categorie": "traitement"},
    {"designation": "Nettoyage de printemps des massifs", "unite": "m2", "prix": 2.40, "categorie": "divers"},
    {"designation": "Bechage de massif", "unite": "m2", "prix": 2.90, "categorie": "divers"},
    {"designation": "Entretien de programmateur d'arrosage", "unite": "unite", "prix": 25.00, "categorie": "divers"},
]
